account/urls.py
from django.urls import path
from account import views

app_name='account'

urlpatterns = [
    path('signup/doctor', views.signup_doctor,name='signup_doctor'),
    path('signup/user',views.signup_ordinary_user,name='signup_ordinary_user'),
    path('login', views.user_login, name='login'),
    path('home',views.home_page,name='home'),
    path('save-data',views.save_data ,name='save_data'),
    path('logout',views.logout_view,name='logout'),
    path('check-symptoms', views.check_symptoms_view, name='check symptoms'),
    path('check-symptoms/<int:pk>',views.check_symptoms_view,name='check symptoms'),
    path('analyze-data',views.analyze_data ,name='analyze data')
]


""" 
    path('signup/user'),
  path('logout/','django.contrib.auth.view.logout',name='logout'),
    path('logout-then-login/', 'django.contrib.auth.view.logout_then_login', name='logout_then_login'),
   

"""

api/urls.py
from django.urls import path

from api import views
from rest_framework.authtoken.views import obtain_auth_token

app_name='api'

urlpatterns = [
    path('symptoms',views.SymptomsView.as_view(),name='symptoms'),
    path('signup/doctor',views.DoctorSignupView.as_view(),name='doctor-signup'),#temporary
    path('signup/user',views.OrdinaryUserView.as_view(),name='user-signup'),
    path('analyze-data', views.analyse_data, name='analyze-data'),
    path('analyze-data-test', views.TestDataView.as_view(), name='analyze-data-test'),

    #path('login',views.Login.as_view(),name='user-signup'),
    path('api-token-auth/',obtain_auth_token),

]

finalfinalproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('api/',include('api.urls')),
    path('api-auth',include('rest_framework.urls'))
]

account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class User(AbstractUser):
    is_doctor=models.BooleanField(default=False)
    is_ordinary_user=models.BooleanField(default=False)

    def __str__(self):
        return self.username

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.first_name

class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    yearsOfExperience=models.IntegerField()
    fieldOfStudy=models.CharField(max_length=100)
    hospital = models.CharField(max_length=100)
    isApproved=models.BooleanField(default=False)

    def __str__(self):
        return self.user.first_name

class OrdinaryUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phoneNumber=models.IntegerField()

    def __str__(self):
        return self.user.first_name

class Symptom(models.Model):
    symptomName=models.CharField(max_length=50)

    def __str__(self):
        return self.symptomName

class Data(models.Model):
    SEX = (
        ('M', 'Male'),
        ('F', 'Female'),

    )

    CHEST_PAIN_TYPE=(
        (1, 'typical angina'),
        (2, 'atypical angina'),
        (3,'non-anginal pain'),
         (4,'asymptomatic'),
    )
    FASTING_BLOOD_SUGER=(
        (1,'fasting blood sugar > 120 mg/dl'),
        (0,'fasting blood sugar < 120 mg/dl')
    )
    REST_ECG=(
        (0,'normal '),
        (1,'having ST-T wave abnormality'),
        (2,'showing probable '),
    )
    EXERCISE_INDUCED_ANGINA=(
        (1 , 'yes'),
        (0,'no'),
    )
    SLOPE=(
        (1,'upsloping'),
        (2, 'flat'),
        (3, 'downsloping'),
    )

    THAL=(
        (3,'normal'),
        (6,'fixed defect'),
        (7,'reversable defect')
    )

    age=models.IntegerField()
    sex=models.CharField(max_length=1,choices=SEX,default='M')
    cp=models.IntegerField(choices=CHEST_PAIN_TYPE,default=1,help_text='chest pain type')
    trestbps=models.DecimalField(decimal_places=2,max_digits=10,help_text='resting blood pressure (in mm Hg on admission to the hospital) ')#
    chol=models.DecimalField(decimal_places=2,max_digits=10,help_text='serum cholestoral in mg/dl')#
    fbs=models.IntegerField(choices=FASTING_BLOOD_SUGER,default=1)
    restecg=models.IntegerField(choices=REST_ECG,default=0,help_text='resting electrocardiographic results ')
    thalach=models.IntegerField(help_text='maximum heart rate achieved ')
    exang=models.IntegerField(choices=EXERCISE_INDUCED_ANGINA,default=1,help_text='exercise induced angina')
    oldpeak=models.IntegerField(help_text='ST depression induced by exercise relative to rest')  #
    slope=models.IntegerField(choices=SLOPE,default=1,help_text='the slope of the peak exercise ST segment ')
    ca=models.IntegerField(help_text='number of major vessels (0-3) colored by flourosopy')
    thal=models.IntegerField(choices=THAL,default=3,help_text='diagnosis of heart disease (angiographic disease status)')

account/forms.py
from random import choice, choices

from django.forms import ModelForm
from django import forms
from account.models import *

class UserForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=User
     #   exclude = ['is_staff','is_doctor','is_superuser','is_active','is_ordinary_user','']
        fields=['first_name','last_name','email','username','password']

class DoctorForm(ModelForm):
    class Meta:
        model=Doctor
        fields=['yearsOfExperience','fieldOfStudy','hospital']


class OrdinaryUserForm(ModelForm):
    class Meta:
        model=OrdinaryUser
        fields=['phoneNumber']


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class SymptomsFrom(forms.Form):
    symptoms=forms.ModelMultipleChoiceField(
        queryset=Symptom.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True,
    )


class DataForm(forms.ModelForm):
    class Meta:
        model = Data
        fields = '__all__'


class SaveDataForm(forms.ModelForm):
    CHOICES=[(1,'Yes')
        ,
             (0,'No')]

    predicted_risk=forms.ChoiceField(choices=CHOICES)

    class Meta:
        model = Data
        fields = '__all__'



class SmokingForm(forms.Form):
    CHOICES=[(1,'Yes ,all most everday'),
             (2,'Yes ,2-4 days a week'),
             (3, 'Yes ,occasionally'),
             (4, 'No ,I donot - drink at all')
             ]
    choices=forms.ChoiceField(choices=CHOICES,widget=forms.RadioSelect,label="Do you drink alcohol?")


class ExerciseForm(forms.Form):
    CHOICES=[(1,'Yes,I exercise everyday'),
             (2,'Yes ,2-3 days a week'),
             (3, 'No,I donot exercise')
             ]
    choices=forms.ChoiceField(choices=CHOICES,widget=forms.RadioSelect,
                              label="Do you exercise?")


class SymptomForm1(forms.Form):
    CHOICES=[('1','chest pain'),
             ('2','indigestion'),
             ('3', 'heartburn'),
             ('4', 'weakness'),
             ('5', 'sweating'),
             ('6', 'shortness of breath'),
             ('7', 'cramping')
             ]
    choices=forms.MultipleChoiceField(choices=CHOICES,widget=forms.CheckboxSelectMultiple,
                              label="We are looking for symptoms of Angina.Which symptoms do you experience? ")

class SymptomForm2(forms.Form):
    CHOICES=[('1','chest discomfort'),
             ('2','coughing'),
             ('3', 'dizziness'),
             ('4', 'vomiting'),
             ('5', 'face seems gray'),
             ('6', 'restlessness'),
             ('7', 'perspiration and clammy skin'),
             ('8', 'an overall feeling of being unwell')
             ]
    choices=forms.MultipleChoiceField(choices=CHOICES,widget=forms.CheckboxSelectMultiple(),
                              label="We are looking for symptoms of Heart attack.\n Which symptoms do you experience?")

class SymptomForm3(forms.Form):
    CHOICES=[(1,'intense tightening in the chest'),
             (2,'air hunger'),
             (3, 'feeling of suffocation'),
             (4, 'breathless after activity '),
             (5, 'short of breath sooner than you \n used to be  after physical activity'),
             ]
    choices=forms.MultipleChoiceField(choices=CHOICES,widget=forms.CheckboxSelectMultiple(),
                              label="What kind of symptoms do you experience ?")

account/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import HttpResponse
from django.shortcuts import render, redirect
import pickle
from account.decorators import doctor_required,ordinary_user_required
#from account.forms import DoctorForm,OrdinaryUserForm,UserForm,LoginForm,SymptomsFrom,DataForm
from account.forms import *
from django.conf import settings
import numpy as np
# Create your views here.


def user_login(request):
    if request.method =='POST':
        form=LoginForm(request.POST)

        if form.is_valid():
            cd=form.cleaned_data

            user=authenticate(username=cd['username'],password=cd['password'])

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('account:home')
                    #return HttpResponse('logged in succesfully')
                else:
                    return HttpResponse('disabled account')
            else :
                return render(request, 'account/login.html', {'form':form,'error':'your username and password didnot match .Please try again'})

    else:
        form=LoginForm()

        return  render(request, 'account/login.html', {'form':form})

def signup_doctor(request):
    if request.method =='POST':

        user_form = UserForm(request.POST)
        doctor_form = DoctorForm(request.POST,request.FILES)

        if user_form.is_valid() and doctor_form.is_valid():
            new_user=user_form.save(commit=False)
            new_user.is_doctor=True
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            new_doctor=doctor_form.save(commit=False)
            new_doctor.user=new_user
            new_doctor.save()

            return HttpResponse("successful")
        else:
            return HttpResponse("error")

    else:
        user_form=UserForm()
        doctor_form=DoctorForm()

        return render(request, 'account/signup_doctor.html',
                      {'user_form': user_form, 'doctor_form':doctor_form})


def signup_ordinary_user(request):
    if request.method =='POST':

        user_form = UserForm(request.POST)
        ordianary_user_form = OrdinaryUserForm(request.POST)

        if user_form.is_valid() and ordianary_user_form.is_valid():
            new_user=user_form.save(commit=False)
            new_user.is_ordinary_user=True
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            new_ordinary_user=ordianary_user_form.save(commit=False)
            new_ordinary_user.user=new_user
            new_ordinary_user.save()

            return HttpResponse("successful")
        else:
            return HttpResponse("error")

    else:
        user_form=UserForm()
        ordianary_user_form=OrdinaryUserForm()

        return render(request, 'account/signup_ordinary_user.html',
                      {'user_form': user_form, 'ordianary_user_form':ordianary_user_form})

@login_required
def logout_view(request):
    logout(request)
    return redirect('account:login')

@login_required
def home_page(request):
    return render(request,'account/home.html')


@login_required
@ordinary_user_required
def check_symptoms_view(request,pk=1):
    if request.method=='GET':
        '''
        if pk==1:
            form= SmokingForm()
            next=2
            previous=0
        elif pk==2:
            form=ExerciseForm()
            next = 3
            previous = 1
        elif pk==3:
            form=SymptomForm1()
            next = 4
            previous = 2
        elif pk==4:
            form=SymptomForm2()
            next = 5
            previous = 3
        elif pk==5:
            form=SymptomForm3()
            next = 0
            previous = 4
        else:
            form=SmokingForm()
            next = 2
            previous = 0 '''
        form1 = SmokingForm(prefix="form1")
        form2 = ExerciseForm(prefix="form2")
        form3 = SymptomForm1(prefix="form3")
        form4 = SymptomForm2(prefix="form4")
        form5 = SymptomForm3(prefix="form5")

       #symptoms_form=SymptomForm1()
        return render(request,'account/check_symptoms.html',{
            'form1':form1,
            'form2': form2,
            'form3': form3,
            'form4': form4,
            'form5': form5,


        })

    elif request.method == 'POST':

        form1 = SmokingForm(request.POST, prefix="form1")
        form2 = ExerciseForm(request.POST, prefix="form2")
        form3 = SymptomForm1(request.POST, prefix="form3")
        form4 = SymptomForm2(request.POST,prefix="form4")
        form5 = SymptomForm3(request.POST,prefix="form5")

        angina = False
        heart_attack = False
        dyspnea = False

        if form3.is_valid():
            if len(form3.cleaned_data['choices']) >= 4:
                angina = True

        if form4.is_valid():
            if len(form4.cleaned_data['choices']) >=4:
                heart_attack=True

        if form5.is_valid():
            if len(form4.cleaned_data['choices']) >=3:
                dyspnea=True

        return render(request, 'account/symptoms_result.html',{
            'angina':angina,
            'heart_attack':heart_attack,
            'dyspnea':dyspnea
        })




@login_required
@doctor_required
def save_data(request):
    if request.method=='GET':
        return render(request,'account/save_data.html')

@login_required
@doctor_required
def save_data(request):
    if request.method=='GET':
        data_from = SaveDataForm()
        return render(request, 'account/save_data.html', {
            'data_form': data_from
        })

    elif request.method=='POST':
        form=DataForm(request.POST)

        if form.is_valid():
            form.save()
        return render(request, 'account/save_data.html', {
            'message': "Data saved succesfully "
        })


@login_required
def analyze_data(request):
    if request.method =='GET':
        data_from=DataForm()
        return render(request,'account/analyze_data.html',{
            'data_form':data_from
        })

    elif request.method=='POST':
        filename=settings.STATIC_ROOT+'finalized_model.sav'
        loaded_model = pickle.load(open(filename, 'rb'))

        data=DataForm(request.POST)
        new_data=data.save(commit=False)

        if new_data.sex=='M':
            sex=1
        else:
            sex=0
        #d=serializers.serialize('json',[new_data,])
        #return HttpResponse(d)

        list=[
            new_data.age,
            sex,
            new_data.cp,
            new_data.trestbps,
            new_data.chol,
            new_data.fbs,
            new_data.restecg,
            new_data.thalach,
            new_data.exang,
            new_data.oldpeak,
            new_data.slope,
            new_data.ca,
            new_data.thal,
        ]

        result=loaded_model.predict([np.array(list)])
        #result = loaded_model.predict([[63.0, 1.0, 1.0, 145.0, 233.0, 1.0, 2.0, 150.0, 0.0, 2.3, 3.0, 0.0, 6.0]])
        #result = loaded_model.predict([[67.0, 1.0, 4.0, 160.0, 286.0, 0.0, 2.0, 108.0, 1.0, 1.5, 2.0, 3.0, 3.0]])

        if result[0]==0:
            result=True
            #return HttpResponse('result no')
        elif result[0]==1:
            result=False
            #return HttpResponse('result yes')

        return render(request, 'account/analysis_result.html', {
                    'result': result
                })

account/templates/base.html
{% extends 'main_base.html' %}
{% load static %}

{% block main-content %}

    <div class="container-fluid">

    {% if request.user.is_authenticated %}



    <!-- Navigation -->
    <a class="menu-toggle rounded" href="#">
      <i class="fa fa-bars"></i>

    </a>

    <nav id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <li class="sidebar-brand">
          <a class="js-scroll-trigger" href="#">

        {% if user.is_ordinary_user %}
          User
        {% elif user.is_doctor %}
          Doctor
        {% endif %}
          </a>
        </li>
        <li class="sidebar-nav-item">
          <a class="js-scroll-trigger" href="{% url 'account:home' %}">Home</a>
        </li>

        {% if user.is_ordinary_user %}


        <li class="sidebar-nav-item">
          <a class="js-scroll-trigger" href="{% url 'account:check symptoms' %}">Check symptoms</a>
        </li>

        {% endif %}

        <li class="sidebar-nav-item">
          <a class="js-scroll-trigger" href="{% url 'account:analyze data' %}">Analyze Data</a>
        </li>

        {% if user.is_doctor %}

        <li class="sidebar-nav-item">
          <a class="js-scroll-trigger" href="{% url 'account:save_data' %}">Save Data</a>
        </li>

        {% endif %}

        <li class="sidebar-nav-item">
          <a class="js-scroll-trigger" href="{% url 'account:logout' %}">Logout</a>
        </li>
      </ul>
    </nav>


    <div class="row">
        {% block content %}

        {% endblock content %}
    </div>

    {% else %}
        <h3>please login</h3>
    {% endif %}


    <!-- Call to Action -->

    <!--
    <section class="content-section bg-primary text-white">
      <div class="container text-center">
        <h2 class="mb-4">The buttons below are impossible to resist...</h2>
        <a href="#" class="btn btn-xl btn-light mr-4">Click Me!</a>
        <a href="#" class="btn btn-xl btn-dark">Look at Me!</a>
      </div>
    </section>
--->

    <!-- Footer -->

    {% block js %}
    {% endblock js %}
    <footer class="footer text-center">
      <div class="container">

        <p class="text-muted small mb-0">Copyright &copy; Final project 2018</p>
      </div>
    </footer>



</div>


<!-- Custom scripts for this template -->
  <script src="{% static 'account/js/stylish-portfolio.js' %}"></script>
{% endblock main-content %}

account/templates/base2.html
{% load static %}

<!doctype html>
<html lang="en">
<head>

    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'account/bootstrap-4/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'account/css/stylish-portfolio.css' %}"/>

    <script src="{% static 'account/js/jquery3.3.1.slim.js' %}"></script>
    <script src="{% static 'account/js/popper.min.js' %}">

    </script>
    <script src="{% static 'account/bootstrap-4/js/bootstrap.min.js' %}"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

</head>
<body>
<div class="container">

{% if request.user.is_authenticated %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Brand</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Add new patient</a>
      </li>
      {% if user.is_doctor %}
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Save data</a>
      </li>
      {% endif %}

      <li class="nav-item">
           <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
      </li>
    </ul>
  </div>
</nav>
{% else %}

{% endif %}

    <div class="row">
        {% block content %}

        {% endblock content%}
    </div>
</div>
</body>
</html>

account/templates/main_base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>

    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'account/bootstrap-4/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'account/css/stylish-portfolio.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'account/font_awesome/css/fontawesome-all.css' %}"/>
    {% block css-content %}
    {% endblock css-content %}

    <script src="{% static 'account/js/jquery3.3.1.slim.js' %}"></script>
    <script src="{% static 'account/js/popper.min.js' %}"></script>
    <script src="{% static 'account/bootstrap-4/js/bootstrap.min.js' %}"></script>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

</head>
<body>

    <div class="row " >
        {% block main-content %}

        {% endblock main-content%}
    </div>


</body>
</html>